apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foundations-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: qa
        #  - env: uat
        #  - env: prod
  template:
    metadata:
      name: 'foundations-{{env}}'
      labels:
        env: '{{env}}'
        domain: foundations
    spec:
      project: default
      source:
        repoURL: https://github.com/selflearner2025/helm-charts.git
        targetRevision: main
        path: foundations-chart
        helm:
          valueFiles:
            - values-{{env}}.yaml    # picks up values-dev.yaml or values-qa.yaml
          values: |
               env: {{env}}              # ‚Üê injected automatically by ApplicationSet
               job-chart:
                  jobName: foundations-bpmn-sync-job-{{env}}
                  configMapName: foundations-management-app-cm-{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: shared-namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true