env: dev                                        # ← add this
configMapName: "foundations-management-app-cm"
artifactName: "bpmn-poc.tar.gz"
artifactSha256: "changing foundation dev thrsday"
artifactUrl: "https://nexus/foundations/dev/v1.0.0.bpmn"

job-chart:
  jobName: "foundations-bpmn-sync-job-dev"           # ← add env suffix
  configMapName: "foundations-management-app-cm-dev" # ← must match configmap name above
  image: "alpine:3.20"
  ttlSecondsAfterFinished: 400
  activeDeadlineSeconds: 600
  backoffLimit: 1
  secretName: "dev-secret" 
