env: dev                                       
configMapName: "claims-management-app-cm"
artifactName: "changing cmais in dev"
artifactSha256: "dev-sha256-placeholder"
artifactUrl: "https://nexus/claims/dev/v1.0.0.bpmn"

job-chart:
  jobName: "claims-bpmn-sync-job-dev"           
  configMapName: "claims-management-app-cm-dev" # ‚Üê must match configmap name above
  image: "alpine:3.20"
  ttlSecondsAfterFinished: 400
  activeDeadlineSeconds: 600
  backoffLimit: 1
  secretName: "dev-secret" 
