configMapName: "claims-management-app-cm"
artifactName: "bpmn-poc.tar.gz"
artifactSha256: "qa-sha256-placeholder"
artifactUrl: "https://nexus/claims/qa/v1.0.0.bpmn"

job-chart:
  jobName: "claims-bpmn-sync-job"
  configMapName: "claims-management-app-cm"
  image: "alpine:3.20"
  ttlSecondsAfterFinished: 400
  activeDeadlineSeconds: 600
  backoffLimit: 1