# default values â€” do not deploy with these directly
configMapName: "claims-management-app-cm"
artifactName: ""
artifactSha256: ""
artifactUrl: ""

# values passed through to job-chart dependency
job-chart:
  jobName: "claims-bpmn-sync-job"
  configMapName: "claims-management-app-cm"
  image: "alpine:3.20"
  ttlSecondsAfterFinished: 400
  activeDeadlineSeconds: 600
  backoffLimit: 1